# List of fluids to be finite.
#
# Fluid section fields:
#   - enabled - If false then the section is ignored. [Required; Type: boolean]
#
#   - id - Fluid ID. Eg "minecraft:water", "lava". [Required; Type: string]
#
#   - allowInfinite - If true and all other 'infinite' conditions in this section are true then the fluid will be infinite. [Optional; Type: boolean]
#
#   - infiniteBiomes - The list of biome ID's in which the fluid will be infinite. [Optional; Type: string list; Empty list ignored]
#
#   - infiniteBiomesCategory - The list of biome categories in which the fluid will be infinite.
#     Possible values: taiga, extreme_hills, jungle, mesa, plains, savanna, icy, the_end,
#     beach, forest, ocean, desert, river, swamp, mushroom, nether. [Optional; Type: string list; Empty list ignored]
#
#   - infiniteDimensions - The list of dimension ID's in which the fluid will be infinite. Possible
#     values for vanilla: overworld, the_nether, the_end. [Optional; Type: string list; Empty list ignored.]
#
#   - minHeight/maxHeight - Minimum/Maximum y-level in which the fluid be infinite. [Optional, Type: integer]
#
# The fluid will be infinite if at least in one of the sections all 'infinite' conditions are true.

[[finiteFluids]]
enabled = false
id = "water"
allowInfinite = true
infiniteBiomes = []
infiniteBiomesCategory = ["river", "ocean", "swamp", "beach"]
infiniteDimensions = []
maxHeight = 62

[[finiteFluids]]
enabled = true
id = "lava"
allowInfinite = true
infiniteBiomes = []
infiniteBiomesCategory = []
infiniteDimensions = ["the_nether"]
maxHeight = 31
